[build]
  publish = "public" # Ganti ini sesuai folder tempat .html kamu disimpan
  functions = "netlify/functions" # Ganti sesuai lokasi file function-mu

[[redirects]]
  from = "/check"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/api/index.js"
  status = 200
